name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to your default branch
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm ci
          npm cache clean --force

      - name: Build
        run: |
          npm run build
        env:
          NODE_ENV: production
          GITHUB_PAGES: 'true'

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: dist/
          retention-days: 5

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist        # The folder the action should deploy
          branch: gh-pages    # The branch the action should deploy to
          clean: true         # Automatically remove deleted files from the deployment
          commit-message: "Deploy to GitHub Pages" # Custom commit message